version: '3.8'

services:
  risk-sense-ai:
    build: .
    container_name: risk-sense-ai
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - NEWS_API_KEY=${NEWS_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/countries"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - risk-sense-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: risk-sense-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - risk-sense-ai
    restart: unless-stopped
    networks:
      - risk-sense-network

networks:
  risk-sense-network:
    driver: bridge

volumes:
  risk-sense-data: